apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  ports:
    - targetPort: 5000
      port: 5000
  selector:
    app: api
---
# for testing in minikube
apiVersion: v1
kind: Service
metadata:
  name: api-np
spec:
  type: NodePort
  ports:
    - targetPort: 5000
      port: 5000
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: tkostas/spam_api:api_v1
          ports:
            - containerPort: 5000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: API_SECRET_KEY
                  name: secrets