apiVersion: v1
kind: Service
metadata:
  name: webapp-np
spec:
  type: NodePort
  ports:
    - targetPort: 5000
      port: 5000
  selector:
    app: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: tkostas/spam_api:webapp_v1
          env:
            - name: API_URL
              value: "http://api-svc:5000/v1/spam-ham"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: WEBAPP_SECRET_KEY
                  name: secrets
          ports:
            - containerPort: 5000